import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CommonLayout from "./common-layout";
import { Suspense } from "react";
import SkeletonLoader from "./components/landing-page/loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}

      >
        <div className="min-h-screen flex flex-col items-center bg-slate-50">
          <main className="w-full max-w-7xl mx-auto">
            <Suspense fallback={<SkeletonLoader />}>
              <CommonLayout>{children}</CommonLayout>
            </Suspense>
          </main>
        </div>


      </body>
    </html>
  );
}
